// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmR9xRL37H6kqPwX3p9lKsWOEOOAfCB2I',
    appId: '1:836432351112:web:56e3c02880c379d4baf43d',
    messagingSenderId: '836432351112',
    projectId: 'welcometodo-b82ca',
    authDomain: 'welcometodo-b82ca.firebaseapp.com',
    storageBucket: 'welcometodo-b82ca.appspot.com',
    measurementId: 'G-8P89FYXQB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKpK8jKO67q2ger4gw-Uclan4q-5l1sY',
    appId: '1:836432351112:android:c473463e8198a449baf43d',
    messagingSenderId: '836432351112',
    projectId: 'welcometodo-b82ca',
    storageBucket: 'welcometodo-b82ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQrnq3mfDXiI1JhMx3rOOjgE13Bdwzjs',
    appId: '1:836432351112:ios:22586b334fda407dbaf43d',
    messagingSenderId: '836432351112',
    projectId: 'welcometodo-b82ca',
    storageBucket: 'welcometodo-b82ca.appspot.com',
    iosBundleId: 'com.example.welcomeTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQrnq3mfDXiI1JhMx3rOOjgE13Bdwzjs',
    appId: '1:836432351112:ios:1082efb3bd258a4abaf43d',
    messagingSenderId: '836432351112',
    projectId: 'welcometodo-b82ca',
    storageBucket: 'welcometodo-b82ca.appspot.com',
    iosBundleId: 'com.example.welcomeTodo.RunnerTests',
  );
}
